model: {
  input_dim: 768,
  hidden_dim: 64,
  output_dim: 1,
  hidden_layers: 2,
  dropout: 0.2,
}
opt: {
  learning_rate: 0.001,
  epochs: 20,
  weight_decay: 0.025,
}
loader: {
  batch_size: 256,
}