num_rel_types= 16
rel_types = {'Explanation', 
             'Continuation',
             'Contrast', 
             'Question-answer_pair',
             'Acknowledgement',
             'Parallel',
             'Comment',
             'Clarification_question',
             'Result',
             'Conditional',
             'Correction',
             'Q-Elab',
             'Alternation',
             'Narration',
             'Elaboration',
             'Background'}